In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

import re, pickle
import functools
import itertools
import string

from string import digits

In [2]:
with open('logit_us.pkl', 'rb') as file:
    clf = pickle.load(file)

In [55]:
with open('../dataset/eng_result.pkl', 'rb') as f:
    eng_result = pickle.load(f)

with open('../dataset/chn_result.pkl', 'rb') as f:
    chn_result = pickle.load(f)

with open('../dataset/port_result.pkl', 'rb') as f:
    port_result = pickle.load(f)

with open('../dataset/spanish_result.pkl', 'rb') as f:
    spanish_result = pickle.load(f)

with open('../dataset/french_result.pkl', 'rb') as f:
    french_result = pickle.load(f)

with open('../dataset/german_result.pkl', 'rb') as f:
    german_result = pickle.load(f)

with open('../dataset/greek_result.pkl', 'rb') as f:
    greek_result = pickle.load(f)

with open('../dataset/hung_result.pkl', 'rb') as f:
    hung_result = pickle.load(f)

with open('../dataset/hindi_result.pkl', 'rb') as f:
    hindi_result = pickle.load(f)

with open('../dataset/irish_result.pkl', 'rb') as f:
    irish_result = pickle.load(f)

with open('../dataset/italian_result.pkl', 'rb') as f:
    italian_result = pickle.load(f)

with open('../dataset/jap_result.pkl', 'rb') as f:
    jap_result = pickle.load(f)

with open('../dataset/arab_result.pkl', 'rb') as f:
    arab_result = pickle.load(f)

with open('../dataset/thai_result.pkl', 'rb') as f:
    thai_result = pickle.load(f)

with open('../dataset/fili_result.pkl', 'rb') as f:
    fili_result = pickle.load(f)

with open('../dataset/viet_result.pkl', 'rb') as f:
    viet_result = pickle.load(f)

with open('../dataset/kor_result.pkl', 'rb') as f:
    kor_result = pickle.load(f)

with open('../dataset/russian_result.pkl', 'rb') as f:
    russian_result = pickle.load(f)

### Preprocess Data

In [37]:
def clean_string(s, aslist=False):
    '''Helper function to clean ingredients'''
    remove_digits = str.maketrans('', '', digits)
    remove_punctuation = str.maketrans('', '', string.punctuation)
    remove_whitespace = str.maketrans('', '', string.whitespace)

    german_ingr = {'zitrone':'lemon', 'zitronen saft':'lemon juice','zwiebel':'onions', 'öl':'oil'}

    # Remove all digits and parenthesis content from ingredients
    tmp = s.translate(remove_punctuation).lower().translate(remove_digits)
    tmp = re.sub(r'\(*\)','',tmp)

    # Remove some stop words
    alist =['low fat', 'reduced fat', 'fat free', 'fatfree', 'nonfat','gluten free', 'free range',
         'reduced sodium', 'salt free','sodium free', 'low sodium', 'sweetened','unsweetened','large','extra large','oz','®','™','oldelpaso','alfredo','knorr'
        ,'hellmannâ','orbestfoodcanolacholesterolfree','€']
    for stra in alist:
        tmp = tmp.replace(stra,'')


    # Normalize ingredient names
    alist = ['chile', 'chili','chilies','chilli','sriracha']

    for pepper in alist:
         if pepper in tmp:
            tmp = 'chili'
            break

    blist = [['flour','flour'],['tumeric','turmeric'],['yoghurt','yogurt'],['yogurt','yogurt'],['sausage','sausage'],['fillet','raw fish'],['mozzarella','mozzarella cheese'],
          ['spinach','spinach']]
    for tup in blist:
        if tup[0] in tmp:
            tmp = tup[1]

    # Translate some ingredient names to english
    if(tmp in german_ingr):
        tmp = german_ingr[tmp]

    # Remove spaces between words that defines an ingredients (e.g. “chicken breast” becomes “chickenbreast”)
    # this step is useful for the tfidf vectorization
    if not aslist:
        tmp = tmp.translate(remove_whitespace)

    return tmp

In [6]:
def generate_text_ingredients(df):
    df.ingredients = df.ingredients.apply(lambda x: list(map(lambda y: clean_string(y, aslist=True), x)))
    df['text_ingredients'] = df['ingredients'].apply(lambda l_ingredients : functools.reduce(lambda acc,x : acc +' ' +x,map(lambda ingred: clean_string(ingred),l_ingredients)))
    return df

In [14]:
eng_df = generate_text_ingredients(eng_result)

In [15]:
chn_df = generate_text_ingredients(chn_result)

In [56]:
port_df = generate_text_ingredients(port_result)

In [17]:
spanish_df = generate_text_ingredients(spanish_result)

In [18]:
french_df = generate_text_ingredients(french_result)

In [33]:
german_df = generate_text_ingredients(german_result)

In [20]:
greek_df = generate_text_ingredients(greek_result)

In [21]:
hung_df = generate_text_ingredients(hung_result)

In [22]:
hindi_df = generate_text_ingredients(hindi_result)

In [34]:
irish_df = generate_text_ingredients(irish_result)

In [39]:
italian_df = generate_text_ingredients(italian_result)

In [25]:
jap_df = generate_text_ingredients(jap_result)

In [41]:
arab_df = generate_text_ingredients(arab_result)

In [43]:
thai_df = generate_text_ingredients(thai_result)

In [45]:
fili_df = generate_text_ingredients(fili_result)

In [29]:
viet_df = generate_text_ingredients(viet_result)

In [30]:
kor_df = generate_text_ingredients(kor_result)

In [47]:
russian_df = generate_text_ingredients(russian_result)

In [49]:
with open('tfidf_vectorizer_us.pkl', 'rb') as file:
    vectorizer = pickle.load(file)

In [50]:
eng_df

,name,ingredients,text_ingredients
0,quinoa salad,"[quinoa, cucumber, cherry tomatoes, red onion,...",quinoa cucumber cherrytomatoes redonion fetach...
1,avocado toast,"[whole grain bread, ripe avocado, lemon juice,...",wholegrainbread ripeavocado lemonjuice salt pe...
2,smoothie bowl,"[fren berries, banana, spinach, almond milk, g...",frenberries banana spinach almondmilk granola ...
3,chickpea curry,"[chickpeas, coconut milk, onion, tomato, garli...",chickpeas coconutmilk onion tomato garlic curr...
4,stuffed bell peppers,"[bell peppers, quinoa, black beans, corn, toma...",bellpeppers quinoa blackbeans corn tomato ched...
...,...,...,...
295,baked salmon,"[raw fish, lemon, dill, olive oil, salt, pepper]",rawfish lemon dill oliveoil salt pepper
296,chicken avocado salad,"[chicken breast, avocado, corn, cilantro, lime...",chickenbreast avocado corn cilantro limejuice ...
297,smoothie bowl,"[fren berries, banana, spinach, almond milk, g...",frenberries banana spinach almondmilk granola ...
298,gluten-free oat pancakes,"[glutenfree oats, banana, eggs, baking powder,...",glutenfreeoats banana eggs bakingpowder vanill...
299,kale chips,"[kale, olive oil, salt]",kale oliveoil salt

### English Version Classification

In [51]:
eng_X = vectorizer.transform(eng_df['text_ingredients'])
eng_pred = clf.predict(eng_X)
eng_df['cuisine'] = eng_pred
eng_df

,name,ingredients,text_ingredients,cuisine
0,quinoa salad,"[quinoa, cucumber, cherry tomatoes, red onion,...",quinoa cucumber cherrytomatoes redonion fetach...,greek
1,avocado toast,"[whole grain bread, ripe avocado, lemon juice,...",wholegrainbread ripeavocado lemonjuice salt pe...,southern_us
2,smoothie bowl,"[fren berries, banana, spinach, almond milk, g...",frenberries banana spinach almondmilk granola ...,brazilian
3,chickpea curry,"[chickpeas, coconut milk, onion, tomato, garli...",chickpeas coconutmilk onion tomato garlic curr...,indian
4,stuffed bell peppers,"[bell peppers, quinoa, black beans, corn, toma...",bellpeppers quinoa blackbeans corn tomato ched...,mexican
...,...,...,...,...
295,baked salmon,"[raw fish, lemon, dill, olive oil, salt, pepper]",rawfish lemon dill oliveoil salt pepper,russian
296,chicken avocado salad,"[chicken breast, avocado, corn, cilantro, lime...",chickenbreast avocado corn cilantro limejuice ...,mexican
297,smoothie bowl,"[fren berries, banana, spinach, almond milk, g...",frenberries banana spinach almondmilk granola ...,brazilian
298,gluten-free oat pancakes,"[glutenfree oats, banana, eggs, baking powder,...",glutenfreeoats banana eggs bakingpowder vanill...,italian
299,kale chips,"[kale, olive oil, salt]",kale oliveoil salt,italian

### Chinese Version Classification

In [52]:
chn_X = vectorizer.transform(chn_df['text_ingredients'])
chn_pred = clf.predict(chn_X)
chn_df['cuisine'] = chn_pred
chn_df

,name,ingredients,text_ingredients,cuisine
0,green salad,"[spinach, kale, cucumber, cherry tomatoes, avo...",spinach kale cucumber cherrytomatoes avocado l...,greek
1,hummus,"[chickpeas, garlic, tahini, olive oil, lemon j...",chickpeas garlic tahini oliveoil lemonjuice sa...,greek
2,grilled salmon,"[salmon, olive oil, lemon, rosemary, salt, bla...",salmon oliveoil lemon rosemary salt blackbean,italian
3,vegetable soup,"[carrot, onion, garlic, celery, broccoli, toma...",carrot onion garlic celery broccoli tomato wat...,filipino
4,oatmeal breakfast,"[oatmeal, milk, fruit, honey, nuts]",oatmeal milk fruit honey nuts,southern_us
...,...,...,...,...
295,grilled mackerel with lime,"[mackerel, lime, ginger slices, garlic, sour b...",mackerel lime gingerslices garlic sourbeans ch...,brazilian
296,vegetable bean stew,"[bean, potato, carrot, cabbage, tomato, zucchi...",bean potato carrot cabbage tomato zucchini bro...,italian
297,roasted pumpkin salad with apples,"[pumpkin, apple, walnut, cranberry, jackfruit,...",pumpkin apple walnut cranberry jackfruit pinea...,moroccan
298,sugar-free cake,"[almond powder, coconut powder, vanilla extrac...",almondpowder coconutpowder vanillaextract cran...,italian
299,quichou,"[oatmeal, honey, almonds, walnuts, yucca necta...",oatmeal honey almonds walnuts yuccanectar fres...,italian

### Portuguese Version Classification

In [58]:
port_X = vectorizer.transform(port_df['text_ingredients'])
port_pred = clf.predict(port_X)
port_df['cuisine'] = port_pred
port_df

,name,ingredients,text_ingredients,cuisine
0,quinoa salad with vegetables,"[quinoa, cucumber, cherry tomato, pepper, lemo...",quinoa cucumber cherrytomato pepper lemon oliv...,greek
1,green smoothie,"[spinach, banana, mango, almond milk, honey, c...",spinach banana mango almondmilk honey chia,brazilian
2,egg white omelet with spinach,"[egg whites, spinach, tomato, feta cheese, sal...",eggwhites spinach tomato fetacheese salt pepper,greek
3,lentil soup,"[lentils, carrots, onions, garlic, thyme, vege...",lentils carrots onions garlic thyme vegetableb...,jamaican
4,grilled chicken salad,"[chicken breast, romaine lettuce, croutons, pa...",chickenbreast romainelettuce croutons parmesan...,italian
...,...,...,...,...
295,guacamole,"[avocado, tomato, onion, cilantro, jalapeño, l...",avocado tomato onion cilantro jalapeño lemon salt,mexican
296,night oats,"[oats, almond milk, yogurt, honey, banana, cin...",oats almondmilk yogurt honey banana cinnamon,greek
297,açaí bowl,"[açaí pulp, banana, strawberry, granola, honey...",açaípulp banana strawberry granola honey cocon...,brazilian
298,tuna salad,"[tuna in water, light mayonnaise, celery, carr...",tunainwater lightmayonnaise celery carrot redo...,american
299,quinoa vegetable salad,"[quinoa, cucumber, cherry tomato, red pepper, ...",quinoa cucumber cherrytomato redpepper redonio...,spanish

### Spanish Version Classification

In [59]:
spanish_X = vectorizer.transform(spanish_df['text_ingredients'])
spanish_pred = clf.predict(spanish_X)
spanish_df['cuisine'] = spanish_pred
spanish_df

,name,ingredients,text_ingredients,cuisine
0,mediterranean salad,"[cherry tomatoes, cucumber, red onion, feta ch...",cherrytomatoes cucumber redonion fetacheese ka...,greek
1,kale and banana smoothie,"[kale, banana, yogurt, honey, almonds, almond ...",kale banana yogurt honey almonds almondmilk,indian
2,quinoa with vegetables,"[quinoa, zucchini, red pepper, onion, garlic, ...",quinoa zucchini redpepper onion garlic vegetab...,italian
3,lentil soup,"[lentils, tomato, carrot, celery, onion, garli...",lentils tomato carrot celery onion garlic cumi...,mexican
4,tofu stir fry,"[tofu, broccoli, carrot, pepper, soy sauce, ga...",tofu broccoli carrot pepper soysauce garlic gi...,chinese
...,...,...,...,...
295,vegetable and hummus wrap,"[whole wheat tortilla, hummus, romaine lettuce...",wholewheattortilla hummus romainelettuce tomat...,greek
296,oatmeal and fruit bowl,"[oatmeal, almond milk, banana, blueberries, al...",oatmeal almondmilk banana blueberries almonds ...,french
297,chickpea and spinach salad,"[chickpeas, spinach, red pepper, onion purple,...",chickpeas spinach redpepper onionpurple lemon ...,moroccan
298,salmon baked with vegetables,"[salmon, asparagus, lemon, pepper, olive oil]",salmon asparagus lemon pepper oliveoil,italian
299,carrot cream,"[carrot, onion, garlic, vegetable broth, cocon...",carrot onion garlic vegetablebroth coconutcrea...,indian